import { IData } from "../../types/components/appTable";

export const data: IData[] = [
  {
    document: "Document.pdf",
    description: "Member agreement bla",
    contractType: "Partnership contract",
    dateUploaded: "09/03/2024",
  },
  {
    document: "Document.pdf",
    description: "Member agreement bla",
    contractType: "Partnership contract",
    dateUploaded: "09/03/2024",
  },
  {
    document: "Document.pdf",
    description: "Member agreement bla",
    contractType: "Partnership contract",
    dateUploaded: "09/03/2024",
  },
  {
    document: "Document.pdf",
    description: "Member agreement bla",
    contractType: "Partnership contract",
    dateUploaded: "09/03/2024",
  },
  {
    document: "Document.pdf",
    description: "Member agreement bla",
    contractType: "Partnership contract",
    dateUploaded: "09/03/2024",
  },
  {
    document: "Document.pdf",
    description: "Member agreement bla",
    contractType: "Partnership contract",
    dateUploaded: "09/03/2024",
  },
  {
    document: "Document.pdf",
    description: "Member agreement bla",
    contractType: "Partnership contract",
    dateUploaded: "09/03/2024",
  },
  {
    document: "Document.pdf",
    description: "Member agreement bla",
    contractType: "Partnership contract",
    dateUploaded: "09/03/2024",
  },
  {
    document: "Document.pdf",
    description: "Member agreement bla",
    contractType: "Partnership contract",
    dateUploaded: "09/03/2024",
  },
  {
    document: "Document.pdf",
    description: "Member agreement bla",
    contractType: "Partnership contract",
    dateUploaded: "09/03/2024",
  },
  {
    document: "Document.pdf",
    description: "Member agreement bla",
    contractType: "Partnership contract",
    dateUploaded: "09/03/2024",
  },
  {
    document: "Document.pdf",
    description: "Member agreement bla",
    contractType: "Partnership contract",
    dateUploaded: "09/03/2024",
  },
  {
    document: "Document.pdf",
    description: "Member agreement bla",
    contractType: "Partnership contract",
    dateUploaded: "09/03/2024",
  },
  {
    document: "Document.pdf",
    description: "Member agreement bla",
    contractType: "Partnership contract",
    dateUploaded: "09/03/2024",
  },
  {
    document: "Document.pdf",
    description: "Member agreement bla",
    contractType: "Partnership contract",
    dateUploaded: "09/03/2024",
  },
  {
    document: "Document.pdf",
    description: "Member agreement bla",
    contractType: "Partnership contract",
    dateUploaded: "09/03/2024",
  },
  {
    document: "Document.pdf",
    description: "Member agreement bla",
    contractType: "Partnership contract",
    dateUploaded: "09/03/2024",
  },
  {
    document: "Document.pdf",
    description: "Member agreement bla",
    contractType: "Partnership contract",
    dateUploaded: "09/03/2024",
  },
  {
    document: "Document.pdf",
    description: "Member agreement bla",
    contractType: "Partnership contract",
    dateUploaded: "09/03/2024",
  },
  {
    document: "Document.pdf",
    description: "Member agreement bla",
    contractType: "Partnership contract",
    dateUploaded: "09/03/2024",
  },
  {
    document: "Document.pdf",
    description: "Member agreement bla",
    contractType: "Partnership contract",
    dateUploaded: "09/03/2024",
  },
  {
    document: "Document.pdf",
    description: "Member agreement bla",
    contractType: "Partnership contract",
    dateUploaded: "09/03/2024",
  },
  {
    document: "Document.pdf",
    description: "Member agreement bla",
    contractType: "Partnership contract",
    dateUploaded: "09/03/2024",
  },
  {
    document: "Document.pdf",
    description: "Member agreement bla",
    contractType: "Partnership contract",
    dateUploaded: "09/03/2024",
  },
];
